### ISSUE TITLE
update_metadata: Need to correct attributes of CLIMDEX variables

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-data-prep#31]
This is an epic (overarching issue or user story).

Problem:

All of the CLIMDEX files formed from BCCAQ (ver 1) downscaled GCM data have the following two problems. It seems likely that other CLIMDEX files generated at PCIC may also.

1. attribute `cell_methods`  is absent or else = `"time: maximum"` (this is incorrect for many indices)
2. attribute `long_name` = CLIMDEX index abbreviation, not the long name

In other BCCAQ CLIMDEX files there are likely similar problems.

Proposed solution:

Add features to `update_metadata` that make it possible to write updates along the following lines:

```
<dependent variable name>:
    cell_methods: = cell_method_for(<dependent variable name>)
    standard_name: = standard_name_for(<dependent variable name>)
```

This innocent bit of specification requires the following features:

- [x] [Access to dependent variable names](https://github.com/pacificclimate/climate-explorer-data-prep/issues/26): so that we can obtain the name of the particular CLIMDEX variable in this file
- [x] [Ability to specify an expression value as a key](https://github.com/pacificclimate/climate-explorer-data-prep/issues/27): so that we can specify the name of the particular CLIMDEX variable in this file (which varies from file to file) as the target (container) for the attribute updates
- [x] Add custom functions (or possibly just dicts) mapping variable name to [cell_methods](https://github.com/pacificclimate/climate-explorer-data-prep/issues/29) and [long_name](https://github.com/pacificclimate/climate-explorer-data-prep/issues/30)

**Comment by rod-glover** [comment]
All component issues closed.
